const SUPPLIERS = { VEDANTA: 1, MRF: 2, CEAT: 3 };
const MANUFACTURERS = { TATA: 1, MARUTI: 2 };
const AUCTION_STATUS = {
  NOT_STARTED: 0,
  PENDING_BID: 1,
  PENDING_VERIFICATION: 2,
  CAN_START: 3,
  AUCTION_ENDED: 4,
};
module.exports = {
  SUPPLIERS,
  MANUFACTURERS,
  AUCTION_STATUS,
};
