const SUPPLIERS = { NULL: 0, VEDANTA: 1, MRF: 2, CEAT: 3 };
const MANUFACTURERS = { NULL: 0, TATA: 1, MARUTI: 2 };

const SUPPLIERS_NAME = ["NULL", "VEDANTA", "MRF", "CEAT"];
const MANUFACTURERS_NAME = ["NULL", "TATA", "MARUTI"];

export { SUPPLIERS, MANUFACTURERS, SUPPLIERS_NAME, MANUFACTURERS_NAME };
